server:
  port: 8080
  ssl:
    enabled: true
    key-store-type: PKCS12
    # The path to the keystore containing the certificate
    key-store: classpath:server.jks
    # The password used to generate the certificate
    key-store-password: 123456
    # The alias mapped to the certificate
    key-alias: 1

logging:
  level:
    org: INFO

spring:
  application:
    name: springboot-ssl


#  security:
#    user:
#      name: admin
#      password: admin