spring:
  application:
    name: rabbitmq-consumer
  rabbitmq:
    # Connect rabbitmq single instance
    # host: localhost
    # port: 5672
    # Connect rabbitmq cluster
    addresses: localhost:5672,localhost:5673,localhost:5674
    username: demouser
    password: demouser
    # 开启发送确认
    publisher-confirm-type: correlated
    # 开启发送失败退回
    publisher-returns: true
    virtual-host: demo

server:
  port: 9080
  region: Singapore

logging:
  level:
    org: INFO



