spring:
  application:
    name: rabbitmq-consumer
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: demouser
    password: demouser
    # 开启发送确认
    publisher-confirm-type: correlated
    # 开启发送失败退回
    publisher-returns: true
    virtual-host: demo

server:
  port: 9080

logging:
  level:
    org: INFO



