apiVersion: v1
kind: Service
metadata:
  name: mysql-loadbalancer
  labels:
    app: mysql
spec:
  ports:
  - port: 33306
    targetPort: 3306
    protocol: TCP
  selector:
    app: mysql
    tier: database
  type: LoadBalancer
status:
  loadBalancer: {}