server:
  port: 9090
  tomcat:
    # 连接数 > max-connections + accept-count，请求并不会被拒绝。请求在OS的连接队列里。
    max-connections: 2
    # Maximum queue length for incoming connection requests when all possible request
    # Does not work: https://stackoverflow.com/questions/50079513/tomcat-and-acceptcount-not-working
    accept-count: 0
    # 空闲连接在关闭前等待的时间
    # connection-timeout: 10s
    threads:
      max: 1
      min-spare: 1
    accesslog:
      enabled: true
      directory: logs
      prefix: access_log

spring:
  application:
    name: handleconnections

logging.level:
  org.apache.tomcat: DEBUG
  org.apache.catalina: DEBUG
