server:
  port: 8080

spring:
  redis:
#    host: 127.0.0.1
#    port: 6379
    password: 111111
    sentinel:
      master: redis-sentinel
      nodes: 127.0.0.1:26379,127.0.0.1:27379,127.0.0.1:28379
      password: 111111
    database: 0
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8
