server:
  port: 9090

logging:
  level:
    root: INFO
    com.b5wang: DEBUG

spring:
  application:
    name: ratelimiting

csp:
  sentinel:
    dashboard:
      server: localhost:8081

#  security:
#    user:
#      name: admin
#      password: admin