server:
  port: 9090

logging:
  level:
    root: INFO
    com.b5wang: DEBUG

spring:
  application:
    name: rate-limiting
#  redis:
#    database: 0
#    host: localhost
#    port: 36379
#    default-timeout: 30000ms
# Above redis config is for springboot2. springboot3 does not work
  data:
    redis:
      database: 0
      host: localhost
      port: 36379
      default-timeout: 30000ms
      lettuce:
        pool:
          min-idle: 0
          max-active: 8
          max-idle: 8
          max-wait: -1ms
#csp:
#  sentinel:
#    dashboard:
#      server: localhost:8081
#  security:
#    user:
#      name: admin
#      password: admin