apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebank-business
  labels:
    app: ebank-business
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ebank-business
  template:
    metadata:
      labels:
        app: ebank-business
    spec:
      containers:
      - name: ebank-business
        image: ebank-business:v0.1
        args: ["--test.arg1=hehe5","--test.arg2=haha5"]
        ports:
        - containerPort: 9001
