apiVersion: v1
kind: Service
metadata:
  name: ebank-business-nodeport
spec:
  selector:
    app: ebank-business
  type: NodePort
  ports:
    - protocol: TCP
      port: 9001
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
      targetPort: 9001
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 31001