server:
  port: 8080

logging:
  level:
    org: INFO

spring:
  application:
    name: redis-sentinel-java
  redis:
    password: 111111
    #    host: 127.0.0.1
    #    port: 6379
    sentinel:
      master: redis-sentinel
      nodes: 127.0.0.1:26379,127.0.0.1:27379,127.0.0.1:28379
    database: 0
    lettuce:
      pool:
        max-idle: 8
        max-active: 8
        min-idle: 0