server:
  port: 8080

logging:
  level:
    org: INFO
    io.lettuce: DEBUG
    io.netty: DEBUG

spring:
  application:
    name: redis-sentinel-java
  data:
    redis:
      password: 111111
      database: 0
      sentinel:
        password: 222222
        master: redis-ha
        nodes:
          - 127.0.0.1:26379
          - 127.0.0.1:27379
          - 127.0.0.1:28379
      lettuce:
        pool:
          max-idle: 8
          max-active: 8
          min-idle: 0
        shutdown-timeout: 200ms