version: '3'
services:
  zookeeper:
    image: zookeeper:3.8.0
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    container_name: "zookeeper"
    restart: "no"
    ports:
      - 2181:2181
    networks:
      - overlay
      
  kafka:
    image: docker.io/bitnami/kafka:3.3
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-0:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    container_name: "kafka"
    restart: "no"
    ports:
      - 9092:9092
    networks:
      - overlay
    depends_on:
      - zookeeper

  logstash:
    image: logstash:7.17.2
    container_name: "logstash"
    restart: "no"
    ports:
      - 4560:4560
    volumes:
      - /opt/mingyue/elk/logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - overlay
    volumes:
      - /opt/mingyue/elk/logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf #挂载logstash的配置文件
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    
    


    
networks:
  overlay:
