apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    app: redis
    tier: cache
  # headless service, Kubernetes does not assign an IP address
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      tier: cache
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis
        tier: cache
    spec:
      containers:
      - image: redis:7
        name: redis
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379