apiVersion: v1
kind: Service
metadata:
  name: redis-loadbalancer
  labels:
    app: redis
spec:
  ports:
  - port: 36379
    targetPort: 6379
    protocol: TCP
  selector:
    app: redis
    tier: cache
  type: LoadBalancer
status:
  loadBalancer: {}