version: '3.1'

services:
  redis-1:
    image: b5wang/redis:6.2
    container_name: redis-1
    command: redis-server --requirepass redis_pwd  --masterauth redis_pwd
    ports:
      - 6379:6379
    volumes:
      - ./data/redis-1:/data

  redis-2:
    image: b5wang/redis:6.2
    container_name: redis-2
    command: redis-server --slaveof redis-1 6379 --requirepass redis_pwd --masterauth redis_pwd
    ports:
      - 6380:6379
    volumes:
      - ./data/redis-2:/data  
    
  redis-3:
    image: b5wang/redis:6.2
    container_name: redis-3
    command: redis-server --slaveof redis-1 6379 --requirepass redis_pwd --masterauth redis_pwd
    ports:
      - 6381:6379
    volumes:
      - ./data/redis-3:/data

  redis-sentinel-1:
    image: b5wang/redis:6.2
    container_name: redis-sentinel-1
    ports:
      - 26379:26379
    command: redis-server /etc/redis/sentinel.conf --sentinel
    restart: always
    volumes:
      - ./sentinel.conf:/etc/redis/sentinel.conf

# join a external network      
networks:
  default:
    external: true
    name: public
