version: '3.1'

services:

  kafka1:
    image: bitnami/kafka:3.3
    container_name: kafka1
    hostname: kafka1
    ports:
      - 9093:9093
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zoo1:2181,zoo2:2181,zoo3:2181/kafka
      - KAFKA_BROKER_ID=1
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka1:9092,EXTERNAL://kafka1:9093
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - ./kafka1/data:/bitnami/kafka
    depends_on:
      - zoo1
      - zoo2
      - zoo3      

  kafka2:
    image: bitnami/kafka:3.3
    container_name: kafka2
    hostname: kafka2
    ports:
      - '9094:9093'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zoo1:2181,zoo2:2181,zoo3:2181/kafka
      - KAFKA_BROKER_ID=2   
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka2:9092,EXTERNAL://kafka2:9093
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - ./kafka2/data:/bitnami/kafka      
    depends_on:
      - zoo1
      - zoo2
      - zoo3
      
  kafka3:
    image: bitnami/kafka:3.3
    container_name: kafka3
    hostname: kafka3
    ports:
      - '9095:9093'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zoo1:2181,zoo2:2181,zoo3:2181/kafka
      - KAFKA_BROKER_ID=3
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka3:9092,EXTERNAL://kafka3:9093
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - ./kafka3/data:/bitnami/kafka
    depends_on:
      - zoo1
      - zoo2
      - zoo3
      